services:

  issue-postgres:
    image: postgres:15
    container_name: issue-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: example12!
      POSTGRES_DB: issue_insight_tracker

    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  issue-minio:
    image: minio/minio:latest
    container_name: issue-minio
    ports:
      - "9000:9000"  
      - "9001:9001"  
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    restart: unless-stopped

    
  issue-web:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: issue-web
    restart: unless-stopped
    ports:
      - "8181:8181"
    depends_on:
      - issue-postgres
      - issue-minio

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: issue-frontend
    restart: unless-stopped
    ports:
      - "4173:4173"
    depends_on:
      - issue-web

volumes:
  mongodb_data:
  postgres_data:
  minio_data: